url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/brf-matteus" # the subpath of your site, e.g. /blog
title: "Brf Matteus" # the name of your site, e.g. ACME Corp.

sass:
  sass_dir: _sass
  style:    compressed